name: CICD pipeline for react app

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout_repository
        uses: actions/checkout@v3
      - name: setup_nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: deploy project
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build