name: CICD pipeline for updating utube content in readme

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  update-readme-with-youtube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8NDpwTbsFSeP7dkbl4hKeQ"

  